# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.11.9                 # https://pyreadiness.org/3.10
  - uv=0.2.33
  #- pip=24.0                      # https://pip.pypa.io/en/stable/news
  - python-dotenv=1.0.1           # https://github.com/theskumar/python-dotenv
  - pip:
    - rpaframework==28.6.1        # https://rpaframework.org/releasenotes.html
    - robocorp==2.1.0             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.3     # https://pypi.org/project/robocorp-browser
    - requests==2.32.3            # https://pypi.org/project/requests
